# Generated by Django 4.0.1 on 2022-01-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        )
    ]
